spring.application.name=finance-tracker

spring.datasource.url=jdbc:postgresql://localhost:5433/finance_tracker
spring.datasource.username=rohan781
spring.datasource.password=rohan781password
spring.jpa.hibernate.ddl-auto=update

jwt.secret=mySmartFinanceTrackerSecretKeyIs123
jwt.expiration=1800000
#only 30 minutes

# users created so far and their password
#rohan781
#rohan@781

#ashwin123
#ashwin@123