spring.application.name=finance-tracker

spring.datasource.url=jdbc:postgresql://localhost:5433/finance_tracker
spring.datasource.username=rohan781
spring.datasource.password=rohan781password
spring.jpa.hibernate.ddl-auto=update
